name: event_ease
description: A comprehensive event services marketplace platform

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.7.3
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.8.5
  firebase_messaging: ^14.6.7
  
  # State management
  provider: ^6.0.5
  
  # UI components
  cupertino_icons: ^1.0.5
  flutter_staggered_grid_view: ^0.7.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.5
  lottie: ^2.3.2
  
  # Utils
  intl: ^0.18.1
  url_launcher: ^6.1.11
  shared_preferences: ^2.1.1
  image_picker: ^1.0.4
  flutter_local_notifications: ^15.1.1
  geolocator: ^10.1.0
  geocoding: ^2.0.5
  google_maps_flutter: ^2.3.0
  flutter_stripe: ^9.3.0
  uuid: ^3.0.7
  flutter_localizations:
    sdk: flutter
  google_fonts: ^5.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6

# Flutter launcher icons configuration
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  # Fonts configuration
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700